name: CI

on: [push]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    env:
      CI: 'true'

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install yarn
        run: npm install -g yarn
      - name: Install dependencies
        run: yarn install
        working-directory: ./docs
      - name: Lint JS
        run: yarn lint:js
        working-directory: ./docs
      - name: Lint HBS
        run: yarn lint:hbs
        working-directory: ./docs
      - name: Test
        run: yarn test
        working-directory: ./docs

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Set up Git
        run: |
          git config --global user.name "Tomster"
          git config --global user.email "tomster@emberjs.com"
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.1.1
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
      - uses: actions/checkout@v1
      - name: Reattach HEAD # https://github.com/actions/checkout/issues/6
        run: |
          git checkout "$(echo ${{ github.ref }} | sed -E 's|refs/[a-zA-Z]+/||')"
      - name: Fetch Git Tags
        run: git fetch --tags
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install yarn
        run: npm install -g yarn
      - name: Install dependencies
        run: yarn install
        working-directory: ./docs
      - name: Deploy
        run: yarn ember deploy production
        working-directory: ./docs
